#!/bin/bash

sudo apt-get update
sudo apt-get install -y apache2 php7.0 libav-tools curl python attr atomicparsley
sudo a2enmod php7.0
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
